## Bin
bin: "bin"

## Input

data_dir: "data"
metadata_file: "data/geo_brca/metadata.csv"
indegree_file: "data/geo_brca/filtered_cos_indegree.csv"

## Results directory:
output_dir: "snakemake_results"

